language: node_js
node_js:
  - 8.11.3
branches:
  only:
    - master
cache: yarn
script:
  - cd theme/yilia/
  - npm run dist
  - cd ../../
  - hexo g
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  target-branch: master
  local-dir: public
  repo: HPDell/HPDell.github.io
